[package]
name = "minesweeper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.3"
rand = "0.8.5"
scrap = "0.5"
opencv = "0.66"
ordered-float = "3.0.0"
enigo = "0.0.14"
